"""Default source configurations for GatherInfo seed data.

Contains the _default_sources() function that returns all built-in
source configurations covering international trade, customs,
regulations, sanctions, and general search sources.
"""


def _default_sources() -> list[dict]:
    """Return seed data for the 16 default sources."""
    return [
        {"id": "wto-eping", "name": "WTO ePing 技术性贸易壁垒通报",
         "description": "WTO 官方 TBT/SPS 通报预警平台，覆盖所有成员国标准更新。",
         "channel": "official", "is_active": True,
         "homepage_url": "https://epingalert.org/",
         "base_url": "https://epingalert.org/en",
         "default_keywords": ["TBT", "SPS", "regulation"],
         "default_categories": ["regulation", "trade"],
         "languages": ["en"], "rate_limit_rps": 0.5,
         "auth_config": {"type": "eping"},
         "legal_basis": "WTO 公开数据"},
        {"id": "cn-fta", "name": "中国自由贸易区服务网",
         "description": "商务部自贸协定数据库：税率查询、原产地规则。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "http://fta.mofcom.gov.cn/",
         "base_url": "http://fta.mofcom.gov.cn/",
         "default_keywords": ["自贸协定", "原产地", "税率"],
         "default_categories": ["fta", "trade"],
         "languages": ["zh"], "country_focus": ["CN"],
         "rate_limit_rps": 0.5, "legal_basis": "公开政府信息"},
        {"id": "ustr", "name": "USTR 美国贸易代表办公室",
         "description": "301 调查、排除清单、美国贸易政策优先级。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://ustr.gov/",
         "base_url": "https://ustr.gov/about-us/policy-offices/press-office/press-releases",
         "default_keywords": ["Section 301", "tariff", "exclusion"],
         "default_categories": ["policy", "trade"],
         "languages": ["en"], "country_focus": ["US"],
         "rate_limit_rps": 0.5, "legal_basis": "美国公开政府信息"},
        {"id": "wco", "name": "WCO 世界海关组织",
         "description": "海关执法行动、海关现代化、风险指标框架。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://www.wcoomd.org/",
         "base_url": "https://www.wcoomd.org/en/media/newsroom.aspx",
         "default_keywords": ["enforcement", "seizure", "customs"],
         "default_categories": ["enforcement", "customs"],
         "languages": ["en"], "rate_limit_rps": 0.5,
         "legal_basis": "WCO 公开信息"},
        {"id": "eu-eurlex", "name": "EU EUR-Lex",
         "description": "欧盟官方法规、指令、决定",
         "channel": "official", "is_active": True,
         "homepage_url": "https://eur-lex.europa.eu/",
         "default_categories": ["regulation"],
         "languages": ["en"], "rate_limit_rps": 0.5,
         "auth_config": {"type": "eurlex"},
         "legal_basis": "欧盟公开法律文件"},
        {"id": "cn-customs", "name": "海关总署公告",
         "description": "中国海关总署：政策法规、商品编码调整、进出口监管公告",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "http://www.customs.gov.cn/",
         "base_url": "http://www.customs.gov.cn/customs/302249/302266/index.html",
         "default_keywords": ["进出口", "关税", "商品编码", "监管", "公告"],
         "default_categories": ["regulation", "trade"],
         "languages": ["zh"], "country_focus": ["CN"],
         "rate_limit_rps": 0.5, "auth_config": {"type": "cn_customs"},
         "legal_basis": "公开政府信息"},
        {"id": "cn-mofcom", "name": "商务部公告",
         "description": "中国商务部：贸易政策、贸易救济调查、出口管制",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "http://www.mofcom.gov.cn/",
         "base_url": "http://www.mofcom.gov.cn/article/zwgk/bnjg/",
         "default_keywords": ["贸易壁垒", "反倾销", "出口管制", "公告"],
         "default_categories": ["policy", "trade"],
         "languages": ["zh"], "country_focus": ["CN"],
         "rate_limit_rps": 0.5, "auth_config": {"type": "cn_mofcom"},
         "legal_basis": "公开政府信息"},
        {"id": "cbp-newsroom", "name": "CBP Newsroom 美国海关查获",
         "description": "毒品、假货、违禁品查获典型案例。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://www.cbp.gov/newsroom",
         "base_url": "https://www.cbp.gov/newsroom/national-media-release",
         "default_keywords": ["seizure", "smuggling", "counterfeit"],
         "default_categories": ["enforcement", "customs"],
         "languages": ["en"], "country_focus": ["US"],
         "rate_limit_rps": 0.5, "legal_basis": "美国公开政府信息"},
        {"id": "imf-commodity-prices", "name": "IMF Primary Commodity Prices",
         "description": "免费、权威的全球能源、农产品、金属价格表。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://www.imf.org/en/Research/commodity-prices",
         "base_url": "https://www.imf.org/en/Research/commodity-prices",
         "default_categories": ["price", "commodity"],
         "languages": ["en"], "rate_limit_rps": 0.5,
         "legal_basis": "IMF 公开数据"},
        {"id": "fao-food-price-index", "name": "FAO Food Price Index",
         "description": "全球谷物、肉类、植物油等价格与供需简报。",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://www.fao.org/worldfoodsituation/foodpricesindex/en/",
         "base_url": "https://www.fao.org/worldfoodsituation/foodpricesindex/en/",
         "default_keywords": ["food", "price", "grain"],
         "default_categories": ["price", "commodity"],
         "languages": ["en"], "rate_limit_rps": 0.5,
         "legal_basis": "FAO 公开数据"},
        {"id": "tavily-search", "name": "Tavily Web 搜索",
         "description": "通用搜索引擎，用于补充性采集，覆盖上述来源未索引的开放信息。",
         "channel": "api_search", "is_active": True,
         "base_url": "https://api.tavily.com",
         "api_endpoint": "/search",
         "api_key_ref": "TAVILY_API_KEY",
         "default_keywords": ["import and export", "tariff", "HS code",
                              "customs supervision", "customs announcement",
                              "customs policy"],
         "default_categories": ["search"],
         "languages": ["zh", "en", "fr", "es", "ar", "pt", "ja", "ko"],
         "rate_limit_rps": 0.5,
         "auth_config": {"prefer_default_keywords": True},
         "legal_basis": "公开互联网信息搜索引擎"},
        # ── Free RSS Feeds (no API key required) ──────────────────────────────────
        {"id": "wto-news-rss", "name": "WTO News (RSS)",
         "description": "WTO official news: trade negotiations, dispute settlement, DG speeches. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.wto.org/",
         "base_url": "https://www.wto.org/english/rss/news_e.xml",
         "default_keywords": ["trade", "dispute", "negotiation", "tariff"],
         "default_categories": ["trade", "policy"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "unctad-rss", "name": "UNCTAD News (RSS)",
         "description": "UN Conference on Trade and Development. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://unctad.org/",
         "base_url": "https://unctad.org/rss.xml",
         "default_keywords": ["trade", "investment", "commodity", "development"],
         "default_categories": ["trade", "market"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "oecd-rss", "name": "OECD News (RSS)",
         "description": "OECD economic surveys, trade policy papers. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.oecd.org/",
         "base_url": "https://www.oecd.org/rss.xml",
         "default_keywords": ["trade", "economy", "tax", "regulation"],
         "default_categories": ["policy", "trade"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "imf-rss", "name": "IMF News (RSS)",
         "description": "IMF press releases, country reports, financial stability. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.imf.org/",
         "base_url": "https://www.imf.org/en/News/RSS",
         "default_keywords": ["economy", "trade", "financial", "stability"],
         "default_categories": ["market", "policy"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "ustr-rss", "name": "USTR Press (RSS)",
         "description": "US Trade Representative press releases. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://ustr.gov/",
         "base_url": "https://ustr.gov/rss/press-releases.xml",
         "default_keywords": ["tariff", "Section 301", "USMCA", "China"],
         "default_categories": ["policy", "tariff"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.5},
        {"id": "usitc-rss", "name": "USITC Releases (RSS)",
         "description": "US International Trade Commission injury determinations. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.usitc.gov/",
         "base_url": "https://www.usitc.gov/rss/releases.xml",
         "default_keywords": ["tariff", "investigation", "antidumping"],
         "default_categories": ["trade_remedy", "tariff"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.5},
        {"id": "cbp-rss", "name": "CBP Newsroom (RSS)",
         "description": "US Customs & Border Protection enforcement news. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.cbp.gov/",
         "base_url": "https://www.cbp.gov/rss/newsroom",
         "default_keywords": ["seizure", "counterfeit", "smuggling", "enforcement"],
         "default_categories": ["enforcement", "customs"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.5},
        {"id": "bis-rss", "name": "BIS Export Control (RSS)",
         "description": "Bureau of Industry and Security export controls. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.bis.gov/",
         "base_url": "https://www.bis.gov/rss.xml",
         "default_keywords": ["export control", "entity list", "EAR", "sanction"],
         "default_categories": ["export_control", "sanction"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.5},
        {"id": "ofac-rss", "name": "OFAC Sanctions (Web)",
         "description": "US Treasury OFAC sanctions announcements. Free public site.",
         "channel": "web_scrape", "is_active": True,
         "homepage_url": "https://ofac.treasury.gov/",
         "base_url": "https://ofac.treasury.gov/sanctions-programs-and-country-information",
         "default_keywords": ["sanction", "OFAC", "SDN", "designation"],
         "default_categories": ["sanction", "compliance"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.3},
        {"id": "eu-trade-rss", "name": "EU Trade News (RSS)",
         "description": "EU trade policy: FTAs, trade defence, CBAM. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://policy.trade.ec.europa.eu/",
         "base_url": "https://policy.trade.ec.europa.eu/news/rss_en",
         "default_keywords": ["trade", "FTA", "CBAM", "anti-dumping", "WTO"],
         "default_categories": ["policy", "trade", "regulation"],
         "languages": ["en"], "country_focus": ["EU"], "rate_limit_rps": 0.5},
        {"id": "eu-tax-customs-rss", "name": "EU Customs & Tax (RSS)",
         "description": "EU customs union developments, tariff classification. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://taxation-customs.ec.europa.eu/",
         "base_url": "https://taxation-customs.ec.europa.eu/rss_en",
         "default_keywords": ["customs", "tariff", "AEO", "classification"],
         "default_categories": ["customs", "regulation"],
         "languages": ["en"], "country_focus": ["EU"], "rate_limit_rps": 0.5},
        {"id": "hk-tid-rss", "name": "香港工贸署 (RSS)",
         "description": "Hong Kong Trade and Industry Dept circulars. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.tid.gov.hk/",
         "base_url": "https://www.tid.gov.hk/english/rss/whatsnew.xml",
         "default_keywords": ["CEPA", "origin", "trade", "circular"],
         "default_categories": ["trade", "policy"],
         "languages": ["en", "zh"], "country_focus": ["HK", "CN"], "rate_limit_rps": 0.5},
        {"id": "singapore-customs-rss", "name": "Singapore Customs (RSS)",
         "description": "Singapore Customs trade facilitation & enforcement. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.customs.gov.sg/",
         "base_url": "https://www.customs.gov.sg/rss.xml",
         "default_keywords": ["customs", "export", "import", "ASEAN"],
         "default_categories": ["customs", "trade"],
         "languages": ["en"], "country_focus": ["SG", "ASEAN"], "rate_limit_rps": 0.5},
        {"id": "asean-rss", "name": "ASEAN News (RSS)",
         "description": "ASEAN economic community updates, ATIGA. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://asean.org/",
         "base_url": "https://asean.org/feed/",
         "default_keywords": ["ASEAN", "trade", "ATIGA", "economic", "RCEP"],
         "default_categories": ["trade", "policy"],
         "languages": ["en"], "country_focus": ["ASEAN"], "rate_limit_rps": 0.5},
        {"id": "adb-rss", "name": "ADB Trade News (RSS)",
         "description": "Asian Development Bank regional trade & supply chains. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.adb.org/",
         "base_url": "https://www.adb.org/rss/news",
         "default_keywords": ["trade", "supply chain", "customs", "regional"],
         "default_categories": ["trade", "logistics"],
         "languages": ["en"], "country_focus": ["ASEAN"], "rate_limit_rps": 0.5},
        {"id": "iisd-rss", "name": "IISD Trade Policy (RSS)",
         "description": "IISD trade & sustainability policy analysis. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.iisd.org/",
         "base_url": "https://www.iisd.org/rss.xml",
         "default_keywords": ["trade", "WTO", "sustainability", "agriculture"],
         "default_categories": ["policy", "trade"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "piie-rss", "name": "PIIE Trade Policy (RSS)",
         "description": "Peterson Institute trade policy research. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.piie.com/",
         "base_url": "https://www.piie.com/rss.xml",
         "default_keywords": ["trade", "tariff", "WTO", "US-China", "sanction"],
         "default_categories": ["policy", "market"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "uk-dbt-rss", "name": "UK Trade (RSS)",
         "description": "UK Dept for Business & Trade: FTAs, trade remedies. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.gov.uk/government/organisations/department-for-business-and-trade",
         "base_url": "https://www.gov.uk/government/organisations/department-for-business-and-trade.atom",
         "default_keywords": ["trade", "FTA", "sanction", "export control", "tariff"],
         "default_categories": ["policy", "trade"],
         "languages": ["en"], "country_focus": ["UK"], "rate_limit_rps": 0.5},
        {"id": "wco-rss", "name": "WCO News (RSS)",
         "description": "World Customs Organization enforcement operations. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.wcoomd.org/",
         "base_url": "https://www.wcoomd.org/en/rss.aspx",
         "default_keywords": ["customs", "enforcement", "SAFE", "HS"],
         "default_categories": ["customs", "enforcement"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "iea-rss", "name": "IEA News (RSS)",
         "description": "International Energy Agency oil market reports. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.iea.org/",
         "base_url": "https://www.iea.org/rss/all",
         "default_keywords": ["oil", "gas", "energy", "price", "supply"],
         "default_categories": ["market", "commodity"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "worldbank-blog-rss", "name": "World Bank Blog (RSS)",
         "description": "World Bank blogs on trade & development. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://blogs.worldbank.org/",
         "base_url": "https://blogs.worldbank.org/rss.xml",
         "default_keywords": ["trade", "commodity", "development", "supply chain"],
         "default_categories": ["market", "policy"],
         "languages": ["en"], "rate_limit_rps": 0.5},


        {"id": "un-news-rss", "name": "UN News (RSS)",
         "description": "United Nations global news: SDGs, trade, humanitarian. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://news.un.org/",
         "base_url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
         "default_keywords": ["trade", "development", "SDG", "climate"],
         "default_categories": ["policy", "trade"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "usda-fas-rss", "name": "USDA FAS 农业贸易 (RSS)",
         "description": "USDA Foreign Agricultural Service: trade data, market intelligence. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://fas.usda.gov/",
         "base_url": "https://fas.usda.gov/rss.xml",
         "default_keywords": ["agriculture", "export", "import", "commodity"],
         "default_categories": ["commodity", "trade"],
         "languages": ["en"], "country_focus": ["US"], "rate_limit_rps": 0.5},
        {"id": "canada-trade-rss", "name": "Canada Trade (RSS)",
         "description": "Global Affairs Canada: trade agreements, export controls. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.international.gc.ca/",
         "base_url": "https://www.international.gc.ca/rss/news-nouvelles.aspx",
         "default_keywords": ["trade", "CETA", "CPTPP", "export"],
         "default_categories": ["policy", "trade"],
         "languages": ["en", "fr"], "country_focus": ["CA"], "rate_limit_rps": 0.5},
        {"id": "japan-meti-rss", "name": "日本經产省 METI (RSS)",
         "description": "Japan Ministry of Economy, Trade and Industry: export controls, trade policy. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.meti.go.jp/",
         "base_url": "https://www.meti.go.jp/english/rss/meti_news.rss",
         "default_keywords": ["export control", "trade", "METI", "Japan"],
         "default_categories": ["policy", "export_control"],
         "languages": ["en", "ja"], "country_focus": ["JP"], "rate_limit_rps": 0.5},
        {"id": "korea-customs-rss", "name": "Korea Customs (RSS)",
         "description": "Korea Customs Service: trade facilitation, enforcement. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.customs.go.kr/",
         "base_url": "https://www.customs.go.kr/english/rss/rss.do",
         "default_keywords": ["customs", "Korea", "FTA", "clearance"],
         "default_categories": ["customs", "trade"],
         "languages": ["en", "ko"], "country_focus": ["KR"], "rate_limit_rps": 0.5},
        {"id": "eu-daily-news-rss", "name": "EU Daily News (RSS)",
         "description": "European Commission daily news: trade, customs, sanctions. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://ec.europa.eu/",
         "base_url": "https://ec.europa.eu/commission/presscorner/api/rss",
         "default_keywords": ["trade", "customs", "sanction", "regulation", "tariff"],
         "default_categories": ["policy", "regulation", "trade"],
         "languages": ["en"], "country_focus": ["EU"], "rate_limit_rps": 0.5},
        {"id": "csis-rss", "name": "CSIS Trade (RSS)",
         "description": "Center for Strategic & International Studies: trade, supply chain, sanctions analysis. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.csis.org/",
         "base_url": "https://www.csis.org/rss.xml",
         "default_keywords": ["trade", "supply chain", "sanction", "China", "technology"],
         "default_categories": ["policy", "trade", "security"],
         "languages": ["en"], "rate_limit_rps": 0.5},
        {"id": "wto-trade-monitoring-rss", "name": "WTO Trade Monitoring (RSS)",
         "description": "WTO trade monitoring reports: G20 trade measures, restrictions. Free RSS feed.",
         "channel": "rss", "is_active": True,
         "homepage_url": "https://www.wto.org/",
         "base_url": "https://www.wto.org/english/rss/tmrd_e.xml",
         "default_keywords": ["trade monitoring", "G20", "restriction", "facilitation"],
         "default_categories": ["trade", "policy"],
         "languages": ["en"], "rate_limit_rps": 0.5},

        # ── 备用源（需配置 API Key 或其他凭据后方可启用）────────────────────
        {"id": "newsapi", "name": "NewsAPI 全球新闻聚合",
         "description": "聚合全球 8 万+ 新闻源，可编程关键词检索（免费版 100 次/天）。需在 https://newsapi.org 注册 API Key。",
         "channel": "json_api", "is_active": False,
         "homepage_url": "https://newsapi.org",
         "base_url": "https://newsapi.org/v2", "api_endpoint": "everything",
         "default_keywords": ["customs", "smuggling", "tariff"],
         "languages": ["en"], "rate_limit_rps": 0.2,
         "auth_config": {
             "method": "GET", "auth": "query", "auth_param": "apiKey",
             "keyword_param": "q", "keyword_join": " OR ",
             "query": {"language": "en", "sortBy": "publishedAt", "pageSize": 50},
             "items_path": "articles",
             "fields": {"title": "title", "content": "content", "summary": "description",
                        "url": "url", "published_at": "publishedAt"}},
         "legal_basis": "公开新闻聚合 API"},
        {"id": "google-alerts", "name": "Google Alerts 快速雷达",
         "description": "监控网络上新出现的关键词。在 Google Alerts 中将提醒输出为 RSS feed，再把该 feed 链接填入 base_url 即可启用。",
         "channel": "rss", "is_active": False,
         "homepage_url": "https://www.google.com/alerts",
         "base_url": "",
         "default_keywords": ["走私", "查获", "tariff", "sanction"],
         "languages": ["zh", "en"], "rate_limit_rps": 0.5,
         "legal_basis": "公开新闻提醒"},
        {"id": "rss-app", "name": "RSS.app 生成源",
         "description": "为没有 RSS 的关键网页生成专属 RSS。生成后把 feed 链接填入 base_url 即可纳入采集。",
         "channel": "rss", "is_active": False,
         "homepage_url": "https://rss.app",
         "base_url": "",
         "languages": ["zh", "en"], "rate_limit_rps": 0.5,
         "legal_basis": "公开网页转 RSS"},
        {"id": "un-comtrade", "name": "UN Comtrade 全球贸易数据库",
         "description": "全球最权威的官方商品贸易统计数据。新版公共 API 需订阅 Key（免费档可申请）。注册地址：https://comtradeplus.un.org/",
         "channel": "json_api", "is_active": False,
         "homepage_url": "https://comtradeplus.un.org/",
         "base_url": "https://comtradeapi.un.org", "api_endpoint": "data/v1/get/C/A/HS",
         "default_categories": ["trade"], "languages": ["en"], "rate_limit_rps": 0.2,
         "auth_config": {
             "method": "GET", "auth": "header", "auth_param": "Ocp-Apim-Subscription-Key",
             "items_path": "data",
             "fields": {"title": "cmdDesc", "content": "partnerDesc", "published_at": "period"}},
         "legal_basis": "联合国公开统计数据"},
        {"id": "itc-trademap", "name": "ITC Trade Map 贸易地图",
         "description": "贸易竞争力、需求市场、关税数据可视化。需在 https://www.trademap.org/ 免费注册账号后访问。",
         "channel": "manual", "is_active": False,
         "homepage_url": "https://www.trademap.org/",
         "default_categories": ["trade"], "languages": ["en"],
         "legal_basis": "ITC 公开数据（需注册）"},
        {"id": "worldbank-open-data", "name": "World Bank Open Data",
         "description": "各国关税、物流绩效、经济指标数据。提供免费公开 JSON API，无需注册即可访问。",
         "channel": "json_api", "is_active": False,
         "homepage_url": "https://data.worldbank.org/",
         "base_url": "https://api.worldbank.org/v2",
         "api_endpoint": "country/all/indicator/TM.TAX.MRCH.WM.AR.ZS",
         "default_categories": ["trade", "economy"], "languages": ["en"], "rate_limit_rps": 0.5,
         "auth_config": {
             "method": "GET", "auth": "none",
             "query": {"format": "json", "per_page": "50"},
             "items_path": "1",
             "fields": {"title": "indicator.value", "content": "value",
                        "published_at": "date", "category": "country.value"}},
         "legal_basis": "世界银行公开数据"},
        {"id": "inoreader", "name": "Inoreader 情报中枢",
         "description": "核心 RSS 情报中枢：订阅所有源、关键词监控、自动翻译。需 OAuth/AppKey。",
         "channel": "json_api", "is_active": False,
         "homepage_url": "https://www.inoreader.com",
         "base_url": "https://www.inoreader.com/reader/api/0",
         "api_endpoint": "stream/contents",
         "languages": ["zh", "en"], "rate_limit_rps": 0.2,
         "auth_config": {
             "method": "GET", "auth": "bearer",
             "items_path": "items",
             "fields": {"title": "title", "content": "summary.content",
                        "url": "canonical.0.href", "published_at": "published"}},
         "legal_basis": "用户自有订阅内容"},
        {"id": "baidu-search", "name": "百度千帆搜索（免费额度）",
         "description": "百度千帆 AI Search / 百度搜索 API。官方免费额度可测试使用，但仍需配置百度千帆 API Key。",
         "channel": "api_search", "is_active": False,
         "homepage_url": "https://cloud.baidu.com/doc/qianfan-api/s/Wmbq4z7e5",
         "base_url": "https://qianfan.baidubce.com", "api_endpoint": "/v2/ai_search/web_search",
         "api_key_ref": "BAIDU_QIANFAN_API_KEY",
         "default_keywords": ["进出口", "关税", "商品编码", "海关监管", "海关公告", "海关政策"],
         "default_categories": ["search", "customs", "tariff"],
         "languages": ["zh"], "rate_limit_rps": 0.3,
         "auth_config": {"search_type": "baidu_qianfan", "prefer_default_keywords": True,
                         "search_source": "baidu_search_v2"},
         "legal_basis": "百度千帆搜索 API 官方免费额度"},
        {"id": "bing-search", "name": "Bing 搜索（需 API Key）",
         "description": "微软 Bing Web Search API，英文搜索质量高。需 Azure 订阅 Key。",
         "channel": "api_search", "is_active": False,
         "homepage_url": "https://www.microsoft.com/en-us/bing/apis/bing-web-search-api",
         "base_url": "https://api.bing.microsoft.com", "api_endpoint": "/v7.0/search",
         "default_categories": ["search"], "languages": ["en", "zh"], "rate_limit_rps": 0.3,
         "auth_config": {"search_type": "bing"},
         "legal_basis": "Bing Web Search API"},
        {"id": "search1api", "name": "Search1API（需 API Key）",
         "description": "聚合搜索 API，支持 Google/Bing/百度等多引擎统一接口。",
         "channel": "api_search", "is_active": False,
         "homepage_url": "https://www.search1api.com/",
         "base_url": "https://api.search1api.com", "api_endpoint": "/search",
         "default_categories": ["search"], "languages": ["zh", "en"], "rate_limit_rps": 0.3,
         "legal_basis": "Search1API 聚合搜索服务"},
        {"id": "australia-dfat-rss", "name": "Australia DFAT Trade (RSS)",
         "description": "澳大利亚外交贸易部新闻 — APAC 核心贸易政策动态。",
         "channel": "rss", "is_active": True, "is_configured": True,
         "homepage_url": "https://www.dfat.gov.au/",
         "base_url": "https://www.dfat.gov.au", "api_endpoint": "/news/rss",
         "default_categories": ["trade", "policy"], "languages": ["en"], "country_focus": ["AU"],
         "legal_basis": "public RSS feed"},

        {"id": "nz-mfat-rss", "name": "New Zealand MFAT Trade (RSS)",
         "description": "新西兰外交贸易部新闻 — 南太平洋区域贸易协定动态。",
         "channel": "rss", "is_active": True, "is_configured": True,
         "homepage_url": "https://www.mfat.govt.nz/",
         "base_url": "https://www.mfat.govt.nz", "api_endpoint": "/en/trade/rss",
         "default_categories": ["trade", "policy"], "languages": ["en"], "country_focus": ["NZ"],
         "legal_basis": "public RSS feed"},

        {"id": "eaeu-rss", "name": "EAEU 欧亚经济联盟 (RSS)",
         "description": "欧亚经济联盟（俄白哈吉亚）技术法规、关税调整通知。覆盖 EAC 认证变化。",
         "channel": "rss", "is_active": True, "is_configured": True,
         "homepage_url": "https://eec.eaeunion.org/",
         "base_url": "https://eec.eaeunion.org", "api_endpoint": "/en/rss/",
         "default_categories": ["trade", "regulation"], "languages": ["en", "ru"], "country_focus": ["RU", "BY", "KZ", "KG", "AM"],
         "legal_basis": "public RSS feed"},

        {"id": "globaltradealert-rss", "name": "Global Trade Alert (RSS)",
         "description": "全球贸易预警 — 跟踪各国保护主义措施、贸易救济动态的独立监测组织。",
         "channel": "rss", "is_active": True, "is_configured": True,
         "homepage_url": "https://www.globaltradealert.org/",
         "base_url": "https://www.globaltradealert.org", "api_endpoint": "/rss.xml",
         "default_categories": ["trade", "policy"], "languages": ["en"],
         "legal_basis": "public RSS feed"},
    ]

