from app.schemas import (
    AuditRecord,
    GraphEdge,
    GraphNode,
    Metric,
    Provenance,
    ReportSection,
    RiskRegion,
    SourceStatus,
    TimelineEvent,
)

GENERATED_AT = "2026-06-01T09:30:00+08:00"

METRICS = [
    Metric(label="新增 TBT/SPS 通报", value="128", delta="+18.4%", trend="up", unit="近 30 天"),
    Metric(label="高风险执法信号", value="42", delta="+11", trend="up", unit="近 7 天"),
    Metric(label="受影响出口货值", value="31.6 亿", delta="-4.2%", trend="down", unit="人民币"),
    Metric(label="信源健康度", value="96.8%", delta="+2.1%", trend="up", unit="在线"),
]

PROVENANCE = {
    "wto-eping": Provenance(
        source_id="wto-eping",
        source_name="WTO ePing SPS/TBT notification feed",
        source_url="https://eping.wto.org/",
        collected_at="2026-06-01T08:55:00+08:00",
        legal_basis="公开官方通报, 遵循站点条款与 robots 策略",
        processing_chain=["rss-ingest", "language-detect", "legal-term-normalize", "entity-linking"],
        quality_score=0.94,
    ),
    "eu-oj": Provenance(
        source_id="eu-oj",
        source_name="Official Journal of the European Union",
        source_url="https://eur-lex.europa.eu/oj/direct-access.html",
        collected_at="2026-06-01T08:40:00+08:00",
        legal_basis="公开官方公报, 仅采集可索引页面",
        processing_chain=["html-render", "article-segment", "nmt-zh", "measure-extraction"],
        quality_score=0.91,
    ),
    "ais-commercial": Provenance(
        source_id="ais-commercial",
        source_name="Licensed AIS anomaly feed",
        source_url="contract://licensed-ais-provider/anomaly-feed",
        collected_at="2026-06-01T08:52:00+08:00",
        legal_basis="商业授权数据, 仅存储派生指标与脱敏线索",
        processing_chain=["api-sync", "geo-normalize", "route-anomaly", "lineage-hash"],
        quality_score=0.88,
    ),
    "social-gray": Provenance(
        source_id="social-gray",
        source_name="Open social and gray-literature radar",
        source_url="https://example.invalid/open-source-radar",
        collected_at="2026-06-01T08:35:00+08:00",
        legal_basis="公开网页与授权订阅, 排除私密群组与绕行访问控制内容",
        processing_chain=["topic-filter", "deduplicate", "claim-check", "risk-tagging"],
        quality_score=0.79,
    ),
}

RISK_REGIONS = [
    RiskRegion(
        id="risk-eu-battery",
        country="欧盟",
        region="西欧",
        latitude=50.85,
        longitude=4.35,
        risk_score=86,
        domain="tbt_sps",
        level="critical",
        drivers=["电池碳足迹申报", "合格评定程序收紧", "供应链尽调"],
        affected_products=["锂电池", "新能源汽车零部件", "储能系统"],
        provenance=PROVENANCE["eu-oj"],
    ),
    RiskRegion(
        id="risk-asean-agri",
        country="东盟重点成员",
        region="东南亚",
        latitude=13.75,
        longitude=100.5,
        risk_score=78,
        domain="biosecurity",
        level="high",
        drivers=["农残限量变更", "口岸检疫抽检加密", "冷链追溯要求"],
        affected_products=["果蔬", "水产品", "预制食品"],
        provenance=PROVENANCE["wto-eping"],
    ),
    RiskRegion(
        id="risk-us-solar",
        country="美国",
        region="北美",
        latitude=38.9,
        longitude=-77.04,
        risk_score=74,
        domain="policy",
        level="high",
        drivers=["原产地审查", "强迫劳动合规核查", "反规避调查"],
        affected_products=["光伏组件", "多晶硅", "逆变器"],
        provenance=PROVENANCE["social-gray"],
    ),
    RiskRegion(
        id="risk-east-africa-route",
        country="东非走廊",
        region="非洲东岸",
        latitude=-4.05,
        longitude=39.67,
        risk_score=69,
        domain="smuggling",
        level="medium",
        drivers=["异常转运停靠", "低报价格聚类", "高风险货代复用"],
        affected_products=["濒危物种制品", "电子废弃物", "高税差消费品"],
        provenance=PROVENANCE["ais-commercial"],
    ),
    RiskRegion(
        id="risk-latam-meat",
        country="南美南部",
        region="拉美",
        latitude=-34.6,
        longitude=-58.38,
        risk_score=61,
        domain="supply_chain",
        level="medium",
        drivers=["兽药残留关注", "港口罢工扰动", "冷链滞港"],
        affected_products=["牛肉", "乳制品", "冷冻禽肉"],
        provenance=PROVENANCE["wto-eping"],
    ),
]

TIMELINE = [
    TimelineEvent(
        id="evt-001",
        occurred_at="2026-06-01T07:40:00+08:00",
        title="欧盟电池法规配套合格评定问答更新",
        country="欧盟",
        domain="tbt_sps",
        severity="critical",
        summary="碳足迹、回收含量与供应链尽调字段出现口径收紧迹象, 涉及出口企业清单需要复核。",
        related_entities=["锂电池", "欧盟委员会", "合格评定机构"],
    ),
    TimelineEvent(
        id="evt-002",
        occurred_at="2026-05-31T22:10:00+08:00",
        title="东南亚多个口岸上调生鲜抽检频次",
        country="东盟重点成员",
        domain="biosecurity",
        severity="high",
        summary="农残与冷链温控记录成为抽检重点, 近 90 天通报模式与去年同期显著不同。",
        related_entities=["水产品", "农残限量", "冷链追溯"],
    ),
    TimelineEvent(
        id="evt-003",
        occurred_at="2026-05-31T18:20:00+08:00",
        title="东非航线出现集装箱路径异常",
        country="东非走廊",
        domain="smuggling",
        severity="medium",
        summary="AIS 派生指标显示部分箱量绕行非惯常港口, 与历史查发案例存在路线重合。",
        related_entities=["蒙巴萨港", "异常转运", "高税差商品"],
    ),
]

SOURCE_STATUS = [
    SourceStatus(
        id="wto-eping",
        name="WTO ePing 官方通报",
        channel="official",
        coverage="TBT/SPS 通报",
        languages=["en", "fr", "es"],
        status="healthy",
        latency_minutes=8,
        last_sync_at="2026-06-01T09:22:00+08:00",
        compliance_note="公开官方数据, 保留原始 URL 与采集哈希。",
    ),
    SourceStatus(
        id="eu-oj",
        name="欧盟官方公报",
        channel="official",
        coverage="法规与执行决定",
        languages=["en", "de", "fr", "es", "it"],
        status="healthy",
        latency_minutes=16,
        last_sync_at="2026-06-01T09:10:00+08:00",
        compliance_note="仅采集可公开访问页面, 遵循站点访问频率限制。",
    ),
    SourceStatus(
        id="licensed-ais",
        name="授权 AIS 异常流",
        channel="commercial",
        coverage="航线、停靠、漂移异常",
        languages=["en"],
        status="healthy",
        latency_minutes=5,
        last_sync_at="2026-06-01T09:25:00+08:00",
        compliance_note="商业授权, 仅输出脱敏派生指标。",
    ),
    SourceStatus(
        id="restricted-deepweb-gate",
        name="深网/暗网授权门禁",
        channel="deepweb",
        coverage="隔离区线索摘要",
        languages=["multi"],
        status="authorization_required",
        latency_minutes=0,
        last_sync_at="not-enabled",
        compliance_note="默认关闭, 需要书面授权、隔离沙箱与全程审计。",
    ),
]

GRAPH_NODES = [
    GraphNode(id="country-eu", label="欧盟", kind="country", risk_score=86, description="电池、碳足迹与供应链尽调风险上升。"),
    GraphNode(id="agency-eu-com", label="欧盟委员会", kind="agency", risk_score=82, description="发布与解释技术法规及配套问答。"),
    GraphNode(id="product-battery", label="锂电池", kind="product", risk_score=88, description="受新一轮合格评定和碳足迹申报影响。"),
    GraphNode(id="measure-carbon", label="碳足迹申报", kind="measure", risk_score=90, description="对数据链、供应商证明与核验口径提出更高要求。"),
    GraphNode(id="country-asean", label="东盟重点成员", kind="country", risk_score=78, description="农残限量和口岸检疫频次波动明显。"),
    GraphNode(id="product-seafood", label="水产品", kind="product", risk_score=72, description="冷链记录、药残与产地证明为关键核验项。"),
    GraphNode(id="port-mombasa", label="蒙巴萨港", kind="port", risk_score=69, description="部分异常转运路径与历史风险案例交叉。"),
    GraphNode(id="event-route", label="异常转运事件簇", kind="event", risk_score=70, description="航线偏离、低报价格与高风险货代复用同时出现。"),
]

GRAPH_EDGES = [
    GraphEdge(id="edge-1", source="agency-eu-com", target="measure-carbon", relation="发布解释", confidence=0.92),
    GraphEdge(id="edge-2", source="measure-carbon", target="product-battery", relation="提高合规成本", confidence=0.88),
    GraphEdge(id="edge-3", source="country-eu", target="agency-eu-com", relation="监管主体", confidence=0.97),
    GraphEdge(id="edge-4", source="country-asean", target="product-seafood", relation="加强抽检", confidence=0.81),
    GraphEdge(id="edge-5", source="port-mombasa", target="event-route", relation="关联停靠", confidence=0.74),
    GraphEdge(id="edge-6", source="event-route", target="product-seafood", relation="疑似夹藏路径", confidence=0.62),
]

REPORT_SECTIONS = [
    ReportSection(
        title="战略态势",
        severity="high",
        body="全球技贸措施继续向低碳、供应链透明度、生物安全与原产地审查集中。欧盟和北美监管动作对高附加值制造出口影响更大。",
        evidence_count=34,
    ),
    ReportSection(
        title="TBT/SPS 重点预警",
        severity="critical",
        body="锂电池碳足迹申报与东盟农残限量调整为今日最高优先级。建议同步标准、商协会与重点企业开展差距核查。",
        evidence_count=27,
    ),
    ReportSection(
        title="战术线索",
        severity="medium",
        body="东非航线异常停靠与低报价格聚类需要进一步比对舱单、历史查发口径和货代关联网络。当前线索仅输出脱敏摘要。",
        evidence_count=11,
    ),
    ReportSection(
        title="模型解释",
        severity="low",
        body="本轮高风险排序主要由通报密度、受影响货值、措施强制性、历史摩擦相似度和路线异常强度共同驱动。",
        evidence_count=18,
    ),
]

AUDIT_RECORDS = [
    AuditRecord(
        id="audit-001",
        artifact="risk-eu-battery",
        source_id="eu-oj",
        algorithm_version="extractor.trade-reg-v0.4.2",
        action="measure_extraction",
        actor="system:data-fusion-foundry",
        timestamp="2026-06-01T08:42:13+08:00",
        decision="accepted: high source quality and deterministic fields matched",
    ),
    AuditRecord(
        id="audit-002",
        artifact="risk-east-africa-route",
        source_id="ais-commercial",
        algorithm_version="route-anomaly-v0.3.1",
        action="derived_signal_export",
        actor="system:compliance-gate",
        timestamp="2026-06-01T08:58:44+08:00",
        decision="accepted: raw identifiers redacted before analyst workspace",
    ),
    AuditRecord(
        id="audit-003",
        artifact="restricted-deepweb-gate",
        source_id="restricted-deepweb-gate",
        algorithm_version="authorization-policy-v1.0.0",
        action="collection_request",
        actor="system:policy-enforcer",
        timestamp="2026-06-01T09:00:00+08:00",
        decision="blocked by default until legal authorization and isolated sandbox are attached",
    ),
]
